version: '3.3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    build: ../backend/foodgram/
    env_file: .env
    volumes:
      - static_foodgram:/backend_static/
      - media_foodgram:/app/media/cats/images/
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ../frontend/
    command: cp -r /app/result_build/. /frontend_static/
    volumes:
      - static_foodgram:/frontend_static
  gateway:
    build: ../nginx/
    # env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_foodgram:/staticfiles/
      - media_foodgram:/media/cats/images/
    depends_on:
      - backend