version: '3.3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kitty:/var/lib/postgresql/data
  backend:
    build: ../backend/foodgram/
    env_file: .env
    volumes:
      - static_foodgram:/backend_static/
      - media_foodgram:/app/media/cats/images/
    depends_on:
      - db